name: Build Tagtune

on: [push, pull_request]

jobs:
  macos-intel-build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: ./action_macos_intel.sh

      - name: Package
        run: tar -czvf tagtune-macos-intel.tar.gz tagtune

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tagtune-macos-intel.tar.gz
          asset_name: tagtune-macos-intel.tar.gz
          asset_content_type: application/gzip
