name: Build Tagtune

on: [push, pull_request]

jobs:
  macos-intel-build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: ./action_macos_intel.sh

      - name: Package
        run: tar -czvf tagtune-macos-intel.tar.gz tagtune

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            tagtune-macos-intel.tar.gz
